# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c10068b03f013b8fd744f5e01bd442b2f020bbcce35d75e9db225c4b92326c5638029519ad87779c54d8870964c71a98d482b83d1146718bd730e0014741cb58

test:
  secret_key_base: 708fc99d0923e9a6bd81b375afbe3590d33ebca477d55aa31a07d7ab5e9338c9d518c0d307dad2a1f40578a2ade417e547498dae73c8a7d61baf91af913a61b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
